# Generated by Django 3.1.7 on 2021-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='normal', max_length=200),
        ),
    ]
